### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by jahnli** [Tencent/tdesign-react-starter#50]
### tdesign 版本

last

### 重现链接

https://tdesign.tencent.com/starter/react/#/dashboard/base

### 重现步骤

TDesign Starter   首页 》 销售渠道     悬停在蓝色块区域 会有文字重叠

### 期望结果

TDesign Starter   首页 》 销售渠道     悬停在蓝色块区域 会有文字重叠

### 实际结果

TDesign Starter   首页 》 销售渠道     悬停在蓝色块区域 会有文字重叠

**Comment by aouos** [comment]
这个应该是 echarts 饼图的问题，series 下的 label 显示和配置 emphasis 的 label 重叠了
