### ISSUE TITLE
github workflows 问题请教

### ISSUE THREAD

**Issue by jincheny** [Tencent/tdesign-react-starter#75]
您好，我复用了您的 issue-assignees.temp.yml 文件，发现几个问题，想向您请教一下。
问题一：我如何才能获取到随机指定的 assignees 并添加到  steps.contributors.outputs.string  位置呢？
```
body: |
            ♥️ 有劳 ${{ steps.contributors.outputs.string }} 尽快确认问题。
            确认有效后将下一步计划和可能需要的时间回复给 @${{ github.event.issue.user.login }} 。
```
问题二： 编写好的脚本如何本地自测呢？
问题三： 您编写的脚本会给开发者连续发两次邮件提示，如何能合并为一个呢？

**Comment by 94dreamer** [comment]
你在哪里复用了 @jincheny

**Comment by jincheny** [comment]
![图片](https://user-images.githubusercontent.com/54785820/169751952-8687deec-bd70-48c4-b26e-f60f555f08e6.png)

我看懂您的写的脚本了，麻烦问您一下，写github action的时候如何调试？
我写的时候是自己建了一个domo仓库反复提交测试。

**Comment by 94dreamer** [comment]
@jincheny 可以像你这样弄个demo反复提交测试，也可以用这个 https://github.com/nektos/act

**Comment by jincheny** [comment]
> @jincheny 可以像你这样弄个demo反复提交测试，也可以用这个 https://github.com/nektos/act

好的，谢谢。
