### ISSUE TITLE
[doc] 文档网站描述中出现 “不相关技术栈” 的使用说明

### ISSUE THREAD

**Issue by Davont** [Tencent/tdesign-react-starter#77]
### tdesign-react-starter 版本

最新版

### 重现链接

https://tdesign.tencent.com/starter/docs/react/deploy

### 重现步骤

打开官网链接：https://tdesign.tencent.com/starter/docs/react/deploy
React 中使用的 路由插件为 `React Router`，并非 `VueRouter`。

**官网**：
<img width="932" alt="图片" src="https://user-images.githubusercontent.com/28757633/170292721-044d13bf-9d7d-4b41-831a-14ab283be673.png">

**package.json**:

<img width="386" alt="图片" src="https://user-images.githubusercontent.com/28757633/170292923-7cf8ef29-eea0-46d5-a111-d8c198658314.png">

### 期望结果

建议改成 将 `<HashRouter>` 改成 `<BrowserRouter>`:

```jsx 
import * as React from "react";
import * as ReactDOM from "react-dom";
import { BrowserRouter } from "react-router-dom";

ReactDOM.render(
  <BrowserRouter>
    {/* The rest of your app goes here */}
  </BrowserRouter>,
  root
);
```

> 参考：https://reactrouter.com/docs/en/v6/routers/browser-router

### 实际结果

<img width="932" alt="图片" src="https://user-images.githubusercontent.com/28757633/170292721-044d13bf-9d7d-4b41-831a-14ab283be673.png">

### 框架版本

React 17.0.2

### 补充说明

似乎文档网站并未开源，无法提 PR。

**Comment by uyarn** [comment]
@Davont 谢谢指正 之前文档改漏了 已经改正了。
另外我们暂时没法默认使用hash router 因为我们这边的部署比较复杂 用hash router可以减少服务器的一些配置。我们的部署又是基于main分支的最新代码触发web hooks 所以暂时默认的还是使用hash router

**Comment by Davont** [comment]
> 
ok的 ，现在看已经改好了，我把 issue 关闭。
